### ISSUE TITLE
phpunit 10 support 

### ISSUE THREAD

**Issue by amrography** [lodeapp/lode#104]
Some options were removed in phpunit 10 like  `printer` and `verbose`

### Proposed solution

I see it's required now to use event system: https://github.com/sebastianbergmann/phpunit/issues/4807 and this might not working for previous versions

### Additional context

![screenshot](https://github.com/lodeapp/lode/assets/9614340/efdac6de-448d-4198-a37a-bdc8d7929cf7)

**Comment by tbuteler** [comment]
Thanks for reporting, @amrography, I'm going to have a look at this as soon as I can.

**Comment by amrography** [comment]
I will try find a solution and open PR for it

**Comment by elliot-putt-clearcare** [comment]
any updates?

**Comment by tbuteler** [comment]
@elliot-putt-clearcare I'm putting the final touches on a large maintenance release and will work on it next, but I'm quite busy with other work so it could still take a while.

**Comment by tbuteler** [comment]
@elliot-putt-clearcare @amrography Lode 0.36 now has preliminary support for PHPUnit 10+. I would welcome any additional testing and feedback 🙏

**Comment by amrography** [comment]
@tbuteler It's working smooth like expected! Thank you for your great effort!
