### ISSUE TITLE
PHPUNIT 10 support issues.

### ISSUE THREAD

**Issue by elliot-putt-clearcare** [lodeapp/lode#119]
### Describe the bug

Hi Guys great package just trying to get your LODE app to scan my tests but getting this error any ideas ? 

LODE version 0.36

PHPUnit 10.3.3 by Sebastian Bergmann and contributors.                                       
                                                                                             
Cannot open bootstrap script "/var/www/html/laraclear/current/.lode/phpunit-10/bootstrap
.PHP"

and  " ERROR  Command "lode_bootstrap=/Users/elliot.        "

Seems like this one above as my mac user folder is eliot.putt the . seems to be breaking the dir structure?                                                                             
         

Im using docker and phpunit 10 with Laravel. 

### Version & OS

![image](https://github.com/user-attachments/assets/bf533fc9-a010-435a-a544-17681c5b9ea5)

![image](https://github.com/user-attachments/assets/f9b82e94-fe81-463c-a18c-401c0ec5eaac)

OR this config 

![image](https://github.com/user-attachments/assets/3f39c823-3aa3-4e14-8a3f-8fedc8f284ed)
![image](https://github.com/user-attachments/assets/a77b04ce-94fd-483f-a0ab-4c02db8db1be)

### Steps to reproduce the behavior

1. Setting up my docker simply trying to connect.

### Expected behavior

Should find my tests

### Actual behavior

Tests are not found following error above.

**Comment by elliot-putt-clearcare** [comment]
Seems to work with this config thanks!
![image](https://github.com/user-attachments/assets/85a2b9c5-04bb-4884-92bb-386ca8c2807e)

**Comment by tbuteler** [comment]
@elliot-putt-clearcare glad you got it sorted. Lode runs commands from the host machine, even on remote environments, so the command itself needs to defer the running of tests to the remote machine, as you've done.

I'll close this issue now, but feel free to open more specific issues if you find them.
