### ISSUE TITLE
[BUG] Can't add repo

### ISSUE THREAD

**Issue by nick322** [lodeapp/lode#48]
### Describe the bug

Add repo show exception 

### Version & OS

mac 11.2
php 7.4
phpunit 9.52
Lode 0.29.1

### Steps to reproduce the behavior

1. Open APP
2. Click on 'Add your first project'
3. Add project
4. choose repo
5. Add repo
6. Save changes
7. See error

### Screenshots

![截圖 2021-02-23 12 48 51](https://user-images.githubusercontent.com/9151347/108803375-7c5ebf00-75d5-11eb-8c59-61760b89e414.png)

### Logs

[lode-2021-02-23.log](https://github.com/lodeapp/lode/files/6026844/lode-2021-02-23.log)

**Comment by tbuteler** [comment]
Thanks for reporting this, @nick322. I've not yet added support for PHPUnit 9+, but I'll look into it as soon as possible.

**Comment by tbuteler** [comment]
@nick322 support for PHPUnit 9+ is coming imminently in 0.30. Thanks again for reporting and for trying out Lode, I really appreciate it.

**Comment by nick322** [comment]
@tbuteler Thanks.😁
