### ISSUE TITLE
Support dark mode for lode

### ISSUE THREAD

**Issue by nick322** [lodeapp/lode#49]
### Describe the feature or problem you’d like to solve

When I use dark mode in mac. 

### Proposed solution

The APP sidebar list can display more clearly in dark mode.

### Additional context

![截圖 2021-02-24 11 50 33](https://user-images.githubusercontent.com/9151347/108944830-84326800-7696-11eb-8a02-2c406b33f2a4.png)

**Comment by tbuteler** [comment]
Ouch, good point. I'm not sure I can get a proper dark mode any time soon, but hopefully make that sidebar a bit more readable won't be too much of a hassle.

**Comment by tbuteler** [comment]
Fixed in [0.30.1](https://github.com/lodeapp/lode/releases/tag/v0.30.1) by removing sidebar vibrancy when in dark mode. Hopefully I can get around to build a dark theme later this year.

**Comment by nick322** [comment]
@tbuteler I appreciate your help very much.
